nama: Game Ular GitHub



pada:

  # Jadwalkan alur kerja untuk berjalan setiap hari pada tengah malam UTC

  jadwal:

    - cron: "0 0 * * *"



  # Izinkan pemicu alur kerja secara manual

  alur kerja_pengiriman:



  # Memicu alur kerja saat mendorong ke cabang utama

  dorongan:

    cabang:

      - utama



Pekerjaan:

  menghasilkan:

    berjalan pada: ubuntu-terbaru

    batas waktu-menit: 10



    tangga:

      # Langkah 1: Periksa repositori

      - nama: Checkout Repository

        penggunaan: tindakan/checkout@v3



      # Langkah 2: Hasilkan animasi ular

      - nama: Hasilkan Kontribusi GitHub Animasi Ular

        kegunaan: Platane/snk@v3

        dengan:

          # Nama pengguna GitHub untuk membuat animasi untuk

          nama_pengguna_github: ${{ pemilik_repositori_github }}



          # Tentukan file output dan konfigurasinya

          keluaran: |

            dist/github-snake.svg

            dist/github-snake-dark.svg?palette=github-dark

            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        lingkungan:

          GITHUB_TOKEN: ${{ rahasia.GITHUB_TOKEN }}



      # Langkah 3: Sebarkan file yang dihasilkan ke cabang 'output'

      - nama: Terapkan ke Cabang Output

        penggunaan: peaceiris/actions-gh-pages@v3

        dengan:

          github_token: ${{ rahasia.GITHUB_TOKEN }}

          direktori_terbit: ./dist

          publikasikan_cabang: keluaran

          # Secara opsional, Anda dapat mengatur pesan komit khusus

          commit_message: "Perbarui animasi ular [lewati ci]"
